### ISSUE TITLE
prop.depend() not working?

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel-react#10]

**Comment by ManuelDeLeon** [comment]
What do you mean? It's there...

``` js
Example({
  name: '',
  autorun() {
    console.log( this.name() );
  },
  render() {
    <div />
  }
})
```

**Comment by fvpDev** [comment]
in docs I guess

**Comment by ManuelDeLeon** [comment]
Ah, I'll add it to my todo list.

**Comment by fvpDev** [comment]
The reason I'm asking is actually because I have this script that hides `<br class="mobile" />` for desktop version of my projects on route change with an autorun, but I was trying to see if there's a way to have it done after info has been replaced in a React class. `prop.depend()` keeps giving me a `depend is not a function` error or just calling the prop like so
`autorun() { this.infos(); this.brDisplay() },`
doesn't work, so I have to do this:
`autorun() { console.log(!!this.infos()); this.brDisplay() },`

**Comment by ManuelDeLeon** [comment]
> I was trying to see if there's a way to have it done after info has been replaced in a React class

Please make a repro. I'm fixing something that smells similar to that but with Signals.

**Comment by ManuelDeLeon** [comment]
I updated the documentation. Create a new issue if you can get a repro working.
