### ISSUE TITLE
Allow React Native

### ISSUE THREAD

**Issue by ManuelDeLeon** [ManuelDeLeon/viewmodel-react#13]
Right now react-dom is a hard dependency. If it's `require('react-dom')`'d  then ViewModel should work with React Native.

That's the theory at least...

**Comment by iwasaki-kenta** [comment]
Definitely want to push for it.

**Comment by ManuelDeLeon** [comment]
All systems are GO...

``` js
import { Text } from 'react-native';

Test({
  render(){
    <Text>Hello from ViewModel!</Text>
  }
})
```

![image](https://cloud.githubusercontent.com/assets/4257750/19701442/abf10374-9ab8-11e6-8e5f-ab5d6f3f37a1.png)

Pick up v1.0.1 and be sure to `import "babel-polyfill";` on index.android.js and index.ios.js

**Comment by ManuelDeLeon** [comment]
Just to be clear, most bindings won't work on native components so you need to wire them manually:

``` js
Example({
  checked: true,
  render() {
    <CheckBox
      label='Label'
      checked={ this.checked() }
      onChange={ (checked) => this.checked(checked) }
    />
  }
});
```

**Comment by iwasaki-kenta** [comment]
So far it seems that say for example with:

```
Example({
  checked: true,
  render() {
    <CheckBox
      label='Label'
      checked={ this.checked() }
      onChange={ (checked) => this.checked(checked) }
    />
  }
});
```

I have to export it out: `export default Example;` or else I'd get an error when passing it around stating `object is not a class, from a string, etc...`. Could it be as a result of my project being configured incorrectly, or something preventing VM from generating the exports?

**Comment by ManuelDeLeon** [comment]
`import { Example } from './Example/Example';`

**Comment by ManuelDeLeon** [comment]
It doesn't export the class as default.

**Comment by iwasaki-kenta** [comment]
Alright, thanks :).

**Comment by ManuelDeLeon** [comment]
I forgot to mention, you can still use "if" and "repeat" bindings because
they happen at compile time. So <CheckBox b="if: prop, repeat: array" /> is
perfectly valid.
