### ISSUE TITLE
ViewModel is undefined (in client console)

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel-react#2]

**Comment by ManuelDeLeon** [comment]
Never seen it. Make a repro.

**Comment by fvpDev** [comment]
https://github.com/fvpDev/vm-react-repro
Type `ViewModel` in console...

**Comment by ManuelDeLeon** [comment]
?

![image](https://cloud.githubusercontent.com/assets/4257750/17677239/249785c0-62ef-11e6-8bb1-e6dfc44e5714.png)

**Comment by fvpDev** [comment]
You did `meteor npm install --save` I assume? Idk what ur output above is. @I typed `ViewModel` and hit return:

![image](https://cloud.githubusercontent.com/assets/10249425/17677884/bbdce8d6-6302-11e6-9726-21482eea0af9.png)

**Comment by ManuelDeLeon** [comment]
Now I get it. ViewModel isn't added to the global scope. If you want it globally then you have to add the following to a js file:

``` js
import ViewModel from 'viewmodel-react';
window.ViewModel = ViewModel;
```

I have to admit I "want" to add it to the global scope but the cons outweigh the pros.

**Comment by fvpDev** [comment]
K kewl. Thanks a lot Manuel!

**Comment by fvpDev** [comment]
Didn't work...

**Comment by ManuelDeLeon** [comment]
It does...

Take the starter (https://github.com/ManuelDeLeon/viewmodel-react-starter) and add the lines to index.js:

``` js
import React from 'react';
import ReactDOM from 'react-dom';
import { App } from './App';

import ViewModel from 'viewmodel-react';
window.ViewModel = ViewModel;

ReactDOM.render(<App />, document.getElementById('root'));
```

`ViewModel` is now available on the console.

**Comment by ManuelDeLeon** [comment]
Maybe the js file you added it to wasn't being loaded.

**Comment by fvpDev** [comment]
Hmmm, I just moved to the jsx file where I had the `ReactDOM.render` function but before it was in a js file that was imported before the jsx...funky. Works now though, thanks
