### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel-react#21]
Hello, Manuel!
1. Docs don't mention any link to this repo.
2. Docs don't have a section re autorun. Although there is a non-working link:
![image](https://cloud.githubusercontent.com/assets/10534563/26551247/37560f4c-448a-11e7-8a18-4c1d5b5cceb8.png)
3. The last line of text in the docs links to Meteor docs, which is not right, right?
![image](https://cloud.githubusercontent.com/assets/10534563/26551284/6bedc1c8-448a-11e7-8dc6-51399e98a018.png)

**Comment by ManuelDeLeon** [comment]
1 & 2: I added https://viewmodel.org/react#BasicsSourceCode and https://viewmodel.org/react#AdvancedAutorun
3. VM-React uses the same Tracker as Meteor so the docs point in the right direction (no need for me to create that documentation if MDG did it already)

Thanks for the help!

**Comment by avalanche1** [comment]
Thx!
btw, I :heart: your Quick Answers section! In fact, reading vm-react docs is by far more pleasant than vm-blaze.
Thank you for all you've done! You're an awesome guy.
