### ISSUE TITLE
Adding ViewModel bindings to existing React Components.

### ISSUE THREAD

**Issue by martineboh** [ManuelDeLeon/viewmodel-react#24]
I am trying to use ViewModel-React with existing React Components from Antd, but it doesn't seems to work. I think ViewModel bindings only work with pure HTML elements, and not ready-made react components like those found in Antd or PUI.
Is there any way to support bindings for React Components...like the Input and Button components of Antd, like this:
```js
import { Input } from 'antd';
<Input placeholder="Antd + ViewModel-React" b="value: inputState"/ >
```

**Comment by ManuelDeLeon** [comment]
You have to use 3rd party components the way they were designed to be used, not with VM bindings. The only bindings that will work are `if`, `repeat`, and `ref`. So if `Input` requires you to pass in a callback for the change event, then that's what you need to do.
