### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel-react#3]
Hi Manuel,
 I just want to know how you can test viewmodel react components (mocha, enzyme...)?
the problem is that components are compiled on meteor build time with your babel plugin and i can't figure out how we can unit test them.

ps: sorry i know this is not an issue but i don't know where i can post this question elsewhere.  
best regards

**Comment by ManuelDeLeon** [comment]
Use Jest.
https://facebook.github.io/jest/docs/tutorial-react.html

See
https://viewmodel.org/#BasicsTesting
