### ISSUE TITLE
Tracker and next VM

### ISSUE THREAD

**Issue by antoninadert** [ManuelDeLeon/viewmodel-react#34]
I thought about your proposal to remove tracker from ViewModel for performance. Why not just putting it as a separate plugin for Viewmodel so we just upgrade VM version but can still support Tracker inside VM if we install the plugin?

Maybe I am naïve to technical considerations so tell me if this is feasible?

This would avoid backward compatibility breaks and would allow a nicer syntax for all meteor users not concerned about performance that much.

**Comment by ManuelDeLeon** [comment]
There's a whole lot of nastiness involved in making Tracker work out of the
box with React render method. Meteor devs would have to pay that tax for
the privilege of not using an autorun or observer. Not to mention I'd have
to maintain a separate babel plugin package.
