### ISSUE TITLE
Focus binding vs. Focus event

### ISSUE THREAD

**Issue by antoninadert** [ManuelDeLeon/viewmodel-react#46]
Hey, I am not sure what to do since focus bindings exist, but what if I want to attach a function that will get executed on the focus event?

As I understood event work like this: `<a b='click:functionName()'>`

so for focus event should it be `<a b='focus:functionName()'>`

but then it is the focus binding, not the focus event...

Some ideas?

**Comment by ManuelDeLeon** [comment]
Use focus without parentheses, it will call your function when the focus
changes, passing a bool parameter.

**Comment by antoninadert** [comment]
Thanks so much 💯
