### ISSUE TITLE
Mixins not working?

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel-react#5]
https://github.com/fvpDev/vm-react-repros

**Comment by ManuelDeLeon** [comment]
You're not loading official.js anywhere.

**Comment by fvpDev** [comment]
Ok, will this is not a vm issue but I'm using meteor still and was wondering what might be the cause of `[0, 0, this.prop(), this.prop2()].join(' ')` not working for me. I'll update with link to my project. If you could help me out that'd be great cuz I'm stumped

**Comment by fvpDev** [comment]
https://github.com/fvpDev/srs1-cch

**Comment by ManuelDeLeon** [comment]
I am SO unhappy with Meteor these days (year?) The freaking update tool takes forever. It's bad enough to have ridiculous wait times between refreshes, it's insane that I can't open repros because Meteor needs to update and the update takes forever. Hopefully it will be ready in the morning...

**Comment by fvpDev** [comment]
I had to uninstall and reinstall, along with installing node 4.4.7, also you'll need Microsoft Build Tools (if you are using Windows). I've had my frustrations with it as well however I think they're making it smoother and working a lot of that out.
