### ISSUE TITLE
How to setup for Meteor ?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel-react#9]
Hi @ManuelDeLeon , I followed your starter project for Express JS based project. Works great!

What's the setup for Meteor like?  I have no idea where to config the 'viewmodel-react-plugin'

**Comment by ManuelDeLeon** [comment]
It's pretty much the same. You add the plug-in configuration to the
.babelrc file at the root of the project. Meteor will pick it up.

**Comment by daveeel** [comment]
I tried use the same .babelrc and `meteor npm i --save-dev ...` almost all the dependencies , just got a lot of babel compiler errors. It'd be great if there's a Meteor starter. Thanks :)

**Comment by ManuelDeLeon** [comment]
I started one but got fed up with  Meteor extracting taking forever. Very
unhappy with Meteor lately. I'll give it another try.

In the meantime follow the instructions in
https://forums.meteor.com/t/viewmodel-for-react-alpha/26490/1

It has a step by step guide to setting it up with Meteor.

**Comment by daveeel** [comment]
By following the instruction in the forum with a new project, it works.

However my issue still persists as I was trying to add viewmodel-react to an existing project. The error message is like:

```
   While processing files with ecmascript (for target web.browser):
   /Users/roger/project/muse/node_modules/viewmodel-react-plugin/dist/index.js:182:17:
   /imports/ui/app/app.jsx: Cannot read property '0' of undefined
   at PluginPass.JSXOpeningElement
   (/Users/roger/project/muse/node_modules/viewmodel-react-plugin/dist/index.js:182:17)
   at newFn
```

The `/imports/ui/app/app.jsx` React source works fine with standard React before adding the vm-react stuff. Would it be possible some issue with viewmodel-react's parsing ?

**Comment by ManuelDeLeon** [comment]
It could be any number of things, old ecmascript, your Babel configuration is using the stage-0 preset, dunno.

**Comment by daveeel** [comment]
Ok thanks. Will check again and report back here if I find the reason.

**Comment by fvpDev** [comment]
This is how I have it set up, not using `.babelrc`:

package.js (might be some extra dependencies, not sure which react ones are related)

```
{
  "dependencies": {
    "react": "^15.3.2",
    "react-addons-pure-render-mixin": "^15.3.2",
    "react-dom": "^15.3.2",
    "viewmodel-react": "^0.8.1",
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-react": "^6.0.15",
    "viewmodel-react-plugin": "^0.7.9"
  },
  "babel": {
    "presets": ["es2015", "react"],
    "plugins": [
      ["viewmodel-react-plugin", {
        "attributes": [
          "id",
          "src", "alt",
          "href", "title", "target",
          "type", "placeholder", "autocomplete",
          "rows", "cols",

          "xlinkHref",
          "viewBox", "width", "height",
          "transform", "x", "y", "cx", "cy", "x1", "y1", "x2", "y2",
          "r", "rx", "ry",
          "d", "points",
          "fill", "fillOpacity", "fillRule",
          "stroke", "strokeOpacity", "strokeWidth",
          "fontSize", "textAnchor", "alignmentBaseline"
        ]
      }]
    ]
  }
}
```

**Comment by ManuelDeLeon** [comment]
I created a Meteor starter project: https://github.com/ManuelDeLeon/viewmodel-react-starter-meteor

I also updated the documentation but the changes are not live yet.
